# Generated by Django 5.1.15 on 2026-06-11 05:17

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('subject_id', models.CharField(help_text='Pseudonym [S|D]CMV[R|D][NN], e.g. SCMVR07. Never a name/MRN/address.', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='subject_id must match [S|D]CMV[R|D][NN], e.g. SCMVR07.', regex='^[SD]CMV[RD]\\d{2}$')])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('subject_id', models.CharField(help_text='Pseudonym [S|D]CMV[R|D][NN], e.g. SCMVR07. Never a name/MRN/address.', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='subject_id must match [S|D]CMV[R|D][NN], e.g. SCMVR07.', regex='^[SD]CMV[RD]\\d{2}$')])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('kt_date', models.DateField(help_text='Transplant date — day 0 for de-identified offsets.')),
                ('donor_serostatus', models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], help_text='Authoritative donor CMV serostatus clinicians acted on at transplant.', max_length=3, null=True)),
                ('recipient_serostatus', models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], help_text='Pre-KT recipient CMV serostatus.', max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDonor',
            fields=[
                ('subject_id', models.CharField(db_index=True, help_text='Pseudonym [S|D]CMV[R|D][NN], e.g. SCMVR07. Never a name/MRN/address.', max_length=12, validators=[django.core.validators.RegexValidator(message='subject_id must match [S|D]CMV[R|D][NN], e.g. SCMVR07.', regex='^[SD]CMV[RD]\\d{2}$')])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical donor',
                'verbose_name_plural': 'historical donors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipient',
            fields=[
                ('subject_id', models.CharField(db_index=True, help_text='Pseudonym [S|D]CMV[R|D][NN], e.g. SCMVR07. Never a name/MRN/address.', max_length=12, validators=[django.core.validators.RegexValidator(message='subject_id must match [S|D]CMV[R|D][NN], e.g. SCMVR07.', regex='^[SD]CMV[RD]\\d{2}$')])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('kt_date', models.DateField(help_text='Transplant date — day 0 for de-identified offsets.')),
                ('donor_serostatus', models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], help_text='Authoritative donor CMV serostatus clinicians acted on at transplant.', max_length=3, null=True)),
                ('recipient_serostatus', models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative')], help_text='Pre-KT recipient CMV serostatus.', max_length=3, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recipient',
                'verbose_name_plural': 'historical recipients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipientVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient')),
            ],
            options={
                'verbose_name': 'historical recipient visit',
                'verbose_name_plural': 'historical recipient visits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecipientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='registry.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCMVSerology',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Snibe Maglumi 600 AU/mL.', max_digits=8)),
                ('drawn_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit')),
            ],
            options={
                'verbose_name': 'historical cmv serology',
                'verbose_name_plural': 'historical cmv serologys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CMVSerology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Snibe Maglumi 600 AU/mL.', max_digits=8)),
                ('drawn_date', models.DateField()),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serologies', to='registry.donor')),
                ('recipient_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serologies', to='registry.recipientvisit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', True), ('recipient_visit__isnull', False)), models.Q(('donor__isnull', False), ('recipient_visit__isnull', True)), _connector='OR'), name='cmvserology_exactly_one_parent')],
            },
        ),
    ]
