# Generated by Django 5.1.15 on 2026-06-19 01:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_create_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOtherCondition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('condition', models.CharField(max_length=120)),
                ('present', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical other condition',
                'verbose_name_plural': 'historical other conditions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OtherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=120)),
                ('present', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('living', 'Living'), ('deceased', 'Deceased')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='relation',
            field=models.CharField(blank=True, help_text='Optional relation to recipient.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('living', 'Living'), ('deceased', 'Deceased')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='relation',
            field=models.CharField(blank=True, help_text='Optional relation to recipient.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecipient',
            name='dialysis_vintage_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecipient',
            name='donor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Paired donor (optional — record may not be entered yet). PROTECT.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor'),
        ),
        migrations.AddField(
            model_name='historicalrecipient',
            name='has_diabetes',
            field=models.BooleanField(blank=True, help_text='Three-state: True / False / Unknown (not asked).', null=True),
        ),
        migrations.AddField(
            model_name='historicalrecipient',
            name='has_hypertension',
            field=models.BooleanField(blank=True, help_text='Three-state: True / False / Unknown (not asked).', null=True),
        ),
        migrations.AddField(
            model_name='historicalrecipient',
            name='induction_agent',
            field=models.CharField(blank=True, choices=[('atg', 'ATG'), ('basiliximab', 'Basiliximab'), ('none', 'None')], help_text="atg / basiliximab / none. 'none' asserts absence; null = not recorded.", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='dialysis_vintage_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='Paired donor (optional — record may not be entered yet). PROTECT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='registry.donor'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='has_diabetes',
            field=models.BooleanField(blank=True, help_text='Three-state: True / False / Unknown (not asked).', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='has_hypertension',
            field=models.BooleanField(blank=True, help_text='Three-state: True / False / Unknown (not asked).', null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='induction_agent',
            field=models.CharField(blank=True, choices=[('atg', 'ATG'), ('basiliximab', 'Basiliximab'), ('none', 'None')], help_text="atg / basiliximab / none. 'none' asserts absence; null = not recorded.", max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.UniqueConstraint(condition=models.Q(('donor__isnull', False)), fields=('donor',), name='cmvserology_at_most_one_per_donor'),
        ),
        migrations.AddField(
            model_name='historicalothercondition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalothercondition',
            name='recipient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient'),
        ),
        migrations.AddField(
            model_name='othercondition',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_conditions', to='registry.recipient'),
        ),
    ]
