# Generated by Django 5.1.15 on 2026-06-19 15:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_cmvserology_result_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMVQuantitative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="COBAS 5000 IU/mL. Null only when result_status='missing'.", max_digits=12, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text="reported = a value was obtained; missing = QC/lab failure (no value). A missing observation never changes the recipient's completion_status.", max_length=8)),
                ('drawn_date', models.DateField()),
            ],
            options={
                'ordering': ['drawn_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCMVQuantitative',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="COBAS 5000 IU/mL. Null only when result_status='missing'.", max_digits=12, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text="reported = a value was obtained; missing = QC/lab failure (no value). A missing observation never changes the recipient's completion_status.", max_length=8)),
                ('drawn_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cmv quantitative',
                'verbose_name_plural': 'historical cmv quantitatives',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='igm_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='missing', help_text="IgM channel. Defaults 'missing' — an IgG-only draw has no IgM observation.", max_length=8),
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='igm_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="IgM channel. Snibe Maglumi 600 AU/mL. Null only when igm_status='missing'.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='igm_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='missing', help_text="IgM channel. Defaults 'missing' — an IgG-only draw has no IgM observation.", max_length=8),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='igm_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="IgM channel. Snibe Maglumi 600 AU/mL. Null only when igm_status='missing'.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cmvserology',
            name='result_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text="IgG channel. reported = a value was obtained; missing = QC/lab failure (no value). A missing observation never changes the recipient's completion_status.", max_length=8),
        ),
        migrations.AlterField(
            model_name='cmvserology',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="IgG channel. Snibe Maglumi 600 AU/mL. Null only when result_status='missing'.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcmvserology',
            name='result_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text="IgG channel. reported = a value was obtained; missing = QC/lab failure (no value). A missing observation never changes the recipient's completion_status.", max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalcmvserology',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="IgG channel. Snibe Maglumi 600 AU/mL. Null only when result_status='missing'.", max_digits=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('igm_status', 'reported'), ('igm_value__isnull', False)), models.Q(('igm_status', 'missing'), ('igm_value__isnull', True)), _connector='OR'), name='cmvserology_igm_value_matches_status'),
        ),
        migrations.AddField(
            model_name='cmvquantitative',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantitatives', to='registry.donor'),
        ),
        migrations.AddField(
            model_name='cmvquantitative',
            name='recipient_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantitatives', to='registry.recipientvisit'),
        ),
        migrations.AddField(
            model_name='historicalcmvquantitative',
            name='donor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor'),
        ),
        migrations.AddField(
            model_name='historicalcmvquantitative',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcmvquantitative',
            name='recipient_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit'),
        ),
        migrations.AddConstraint(
            model_name='cmvquantitative',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', True), ('recipient_visit__isnull', False)), models.Q(('donor__isnull', False), ('recipient_visit__isnull', True)), _connector='OR'), name='cmvquantitative_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='cmvquantitative',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result_status', 'reported'), ('value__isnull', False)), models.Q(('result_status', 'missing'), ('value__isnull', True)), _connector='OR'), name='cmvquantitative_value_matches_result_status'),
        ),
    ]
