# Generated by Django 5.1.15 on 2026-06-19 21:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_cmvquantitative_historicalcmvquantitative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDrugLevel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('analyte', models.CharField(choices=[('tacrolimus', 'Tacrolimus'), ('everolimus', 'Everolimus')], max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="Trough concentration, ng/mL. Null only when result_status='missing'.", max_digits=8, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text='reported = a value was obtained; missing = QC/lab failure (no value).', max_length=8)),
                ('drawn_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit')),
            ],
            options={
                'verbose_name': 'historical drug level',
                'verbose_name_plural': 'historical drug levels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRenalFunction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serum_creatinine_mg_dl', models.DecimalField(blank=True, decimal_places=2, help_text="Raw serum creatinine, mg/dL. Null only when result_status='missing'.", max_digits=6, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text='reported = a value was obtained; missing = QC/lab failure (no value).', max_length=8)),
                ('drawn_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit')),
            ],
            options={
                'verbose_name': 'historical renal function',
                'verbose_name_plural': 'historical renal functions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTBNKPanel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cd3_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd3_cd4_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD4+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_cd4_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD4+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd3_cd8_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD8+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_cd8_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD8+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd19_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD19+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd19_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD19+ % of lymphocytes.', max_digits=5, null=True)),
                ('nk_count', models.DecimalField(blank=True, decimal_places=2, help_text='NK CD3−CD16+CD56+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('nk_pct', models.DecimalField(blank=True, decimal_places=2, help_text='NK CD3−CD16+CD56+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd4_cd8_dp_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD4+CD8+ double-positive absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd4_cd8_dp_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD4+CD8+ double-positive % of lymphocytes.', max_digits=5, null=True)),
                ('cd4_cd8_dn_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD4−CD8− double-negative absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd4_cd8_dn_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD4−CD8− double-negative % of lymphocytes.', max_digits=5, null=True)),
                ('drawn_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_visit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit')),
            ],
            options={
                'verbose_name': 'historical tbnk panel',
                'verbose_name_plural': 'historical tbnk panels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DrugLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyte', models.CharField(choices=[('tacrolimus', 'Tacrolimus'), ('everolimus', 'Everolimus')], max_length=16)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="Trough concentration, ng/mL. Null only when result_status='missing'.", max_digits=8, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text='reported = a value was obtained; missing = QC/lab failure (no value).', max_length=8)),
                ('drawn_date', models.DateField()),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_levels', to='registry.donor')),
                ('recipient_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_levels', to='registry.recipientvisit')),
            ],
            options={
                'ordering': ['drawn_date', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', True), ('recipient_visit__isnull', False)), models.Q(('donor__isnull', False), ('recipient_visit__isnull', True)), _connector='OR'), name='druglevel_exactly_one_parent'), models.CheckConstraint(condition=models.Q(models.Q(('result_status', 'reported'), ('value__isnull', False)), models.Q(('result_status', 'missing'), ('value__isnull', True)), _connector='OR'), name='druglevel_value_matches_result_status')],
            },
        ),
        migrations.CreateModel(
            name='RenalFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_creatinine_mg_dl', models.DecimalField(blank=True, decimal_places=2, help_text="Raw serum creatinine, mg/dL. Null only when result_status='missing'.", max_digits=6, null=True)),
                ('result_status', models.CharField(choices=[('reported', 'Reported'), ('missing', 'Missing')], default='reported', help_text='reported = a value was obtained; missing = QC/lab failure (no value).', max_length=8)),
                ('drawn_date', models.DateField()),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renal_functions', to='registry.donor')),
                ('recipient_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renal_functions', to='registry.recipientvisit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', True), ('recipient_visit__isnull', False)), models.Q(('donor__isnull', False), ('recipient_visit__isnull', True)), _connector='OR'), name='renalfunction_exactly_one_parent'), models.CheckConstraint(condition=models.Q(models.Q(('result_status', 'reported'), ('serum_creatinine_mg_dl__isnull', False)), models.Q(('result_status', 'missing'), ('serum_creatinine_mg_dl__isnull', True)), _connector='OR'), name='renalfunction_value_matches_result_status')],
            },
        ),
        migrations.CreateModel(
            name='TBNKPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd3_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd3_cd4_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD4+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_cd4_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD4+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd3_cd8_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD8+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd3_cd8_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD3+CD8+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd19_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD19+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd19_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD19+ % of lymphocytes.', max_digits=5, null=True)),
                ('nk_count', models.DecimalField(blank=True, decimal_places=2, help_text='NK CD3−CD16+CD56+ absolute count, cells/µL.', max_digits=10, null=True)),
                ('nk_pct', models.DecimalField(blank=True, decimal_places=2, help_text='NK CD3−CD16+CD56+ % of lymphocytes.', max_digits=5, null=True)),
                ('cd4_cd8_dp_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD4+CD8+ double-positive absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd4_cd8_dp_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD4+CD8+ double-positive % of lymphocytes.', max_digits=5, null=True)),
                ('cd4_cd8_dn_count', models.DecimalField(blank=True, decimal_places=2, help_text='CD4−CD8− double-negative absolute count, cells/µL.', max_digits=10, null=True)),
                ('cd4_cd8_dn_pct', models.DecimalField(blank=True, decimal_places=2, help_text='CD4−CD8− double-negative % of lymphocytes.', max_digits=5, null=True)),
                ('drawn_date', models.DateField()),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbnk_panels', to='registry.donor')),
                ('recipient_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbnk_panels', to='registry.recipientvisit')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', True), ('recipient_visit__isnull', False)), models.Q(('donor__isnull', False), ('recipient_visit__isnull', True)), _connector='OR'), name='tbnkpanel_exactly_one_parent')],
            },
        ),
    ]
