# Generated by Django 5.1.15 on 2026-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_historicaldruglevel_historicalrenalfunction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmvquantitative',
            name='severity_tier',
            field=models.CharField(choices=[('asymptomatic', 'Asymptomatic'), ('syndrome', 'Syndrome'), ('disease', 'Disease')], default='asymptomatic', help_text="Clinical Kotton-2018 tier (asymptomatic/syndrome/disease) for this draw. Symptom-based, NOT value-derived; an episode's tier = the max among its members.", max_length=12),
        ),
        migrations.AddField(
            model_name='historicalcmvquantitative',
            name='severity_tier',
            field=models.CharField(choices=[('asymptomatic', 'Asymptomatic'), ('syndrome', 'Syndrome'), ('disease', 'Disease')], default='asymptomatic', help_text="Clinical Kotton-2018 tier (asymptomatic/syndrome/disease) for this draw. Symptom-based, NOT value-derived; an episode's tier = the max among its members.", max_length=12),
        ),
    ]
