# Generated by Django 5.1.15 on 2026-06-21 00:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_cmvquantitative_severity_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedicationCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('drug_class', models.CharField(choices=[('antiviral', 'Antiviral'), ('immunosuppressant', 'Immunosuppressant')], max_length=18)),
                ('agent', models.CharField(help_text='Drug name, e.g. valganciclovir, tacrolimus.', max_length=64)),
                ('dose_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dose_unit', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mg_kg', 'mg/kg'), ('mg_m2', 'mg/m²')], max_length=6)),
                ('frequency', models.CharField(choices=[('qd', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qod', 'Every other day'), ('weekly', 'Weekly')], max_length=8)),
                ('course_type', models.CharField(choices=[('prophylaxis', 'Prophylaxis'), ('treatment', 'Treatment')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = ongoing.', null=True)),
                ('completed_per_protocol', models.BooleanField(blank=True, help_text='Prophylaxis only. Three-state: True/False/Unknown.', null=True)),
                ('early_discontinuation_reason', models.CharField(blank=True, choices=[('toxicity', 'Toxicity'), ('intolerance', 'Intolerance'), ('cost', 'Cost'), ('other', 'Other')], help_text='Prophylaxis only. Blank when not discontinued early.', max_length=12)),
                ('dose_reduction_count', models.PositiveIntegerField(blank=True, help_text='Treatment only. Number of dose reductions.', null=True)),
                ('dose_reduction_reason', models.CharField(blank=True, help_text='Treatment only.', max_length=120)),
                ('change_direction', models.CharField(blank=True, choices=[('reduction', 'Reduction'), ('intensification', 'Intensification')], help_text='Immunosuppressant only. Reduction vs intensification.', max_length=15)),
                ('cmv_management_intent', models.BooleanField(blank=True, help_text='Three-state: was this IS change made to manage CMV? True/False/Unknown.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient')),
            ],
            options={
                'verbose_name': 'historical medication course',
                'verbose_name_plural': 'historical medication courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRejectionEpisode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('onset_date', models.DateField()),
                ('rejection_type', models.CharField(choices=[('tcmr', 'TCMR'), ('amr', 'AMR'), ('mixed', 'Mixed')], max_length=8)),
                ('banff_grade', models.CharField(blank=True, choices=[('borderline', 'Borderline'), ('ia', 'IA'), ('ib', 'IB'), ('iia', 'IIA'), ('iib', 'IIB'), ('iii', 'III'), ('amr_active', 'Active AMR'), ('amr_chronic', 'Chronic active AMR')], max_length=12)),
                ('biopsy_proven', models.BooleanField(default=False)),
                ('biopsy_date', models.DateField(blank=True, null=True)),
                ('treatment', models.CharField(blank=True, max_length=120)),
                ('resolved_date', models.DateField(blank=True, help_text='Null = unresolved.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient')),
            ],
            options={
                'verbose_name': 'historical rejection episode',
                'verbose_name_plural': 'historical rejection episodes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_class', models.CharField(choices=[('antiviral', 'Antiviral'), ('immunosuppressant', 'Immunosuppressant')], max_length=18)),
                ('agent', models.CharField(help_text='Drug name, e.g. valganciclovir, tacrolimus.', max_length=64)),
                ('dose_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dose_unit', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mg_kg', 'mg/kg'), ('mg_m2', 'mg/m²')], max_length=6)),
                ('frequency', models.CharField(choices=[('qd', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qod', 'Every other day'), ('weekly', 'Weekly')], max_length=8)),
                ('course_type', models.CharField(choices=[('prophylaxis', 'Prophylaxis'), ('treatment', 'Treatment')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = ongoing.', null=True)),
                ('completed_per_protocol', models.BooleanField(blank=True, help_text='Prophylaxis only. Three-state: True/False/Unknown.', null=True)),
                ('early_discontinuation_reason', models.CharField(blank=True, choices=[('toxicity', 'Toxicity'), ('intolerance', 'Intolerance'), ('cost', 'Cost'), ('other', 'Other')], help_text='Prophylaxis only. Blank when not discontinued early.', max_length=12)),
                ('dose_reduction_count', models.PositiveIntegerField(blank=True, help_text='Treatment only. Number of dose reductions.', null=True)),
                ('dose_reduction_reason', models.CharField(blank=True, help_text='Treatment only.', max_length=120)),
                ('change_direction', models.CharField(blank=True, choices=[('reduction', 'Reduction'), ('intensification', 'Intensification')], help_text='Immunosuppressant only. Reduction vs intensification.', max_length=15)),
                ('cmv_management_intent', models.BooleanField(blank=True, help_text='Three-state: was this IS change made to manage CMV? True/False/Unknown.', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_courses', to='registry.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='RejectionEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_date', models.DateField()),
                ('rejection_type', models.CharField(choices=[('tcmr', 'TCMR'), ('amr', 'AMR'), ('mixed', 'Mixed')], max_length=8)),
                ('banff_grade', models.CharField(blank=True, choices=[('borderline', 'Borderline'), ('ia', 'IA'), ('ib', 'IB'), ('iia', 'IIA'), ('iib', 'IIB'), ('iii', 'III'), ('amr_active', 'Active AMR'), ('amr_chronic', 'Chronic active AMR')], max_length=12)),
                ('biopsy_proven', models.BooleanField(default=False)),
                ('biopsy_date', models.DateField(blank=True, null=True)),
                ('treatment', models.CharField(blank=True, max_length=120)),
                ('resolved_date', models.DateField(blank=True, help_text='Null = unresolved.', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_episodes', to='registry.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, help_text='Null = still admitted.', null=True)),
                ('reason', models.CharField(help_text='All-cause reason. Free text — never exported (leak vector).', max_length=120)),
                ('disposition', models.CharField(blank=True, choices=[('discharged_home', 'Discharged home'), ('transferred', 'Transferred'), ('died', 'Died'), ('against_advice', 'Against medical advice')], max_length=16)),
                ('cmv_attributable', models.BooleanField(default=False, help_text='Honest-denominator flag (US 36): reviewer judgement that the admission is CMV-attributable. Independent of cmv_attribution.')),
                ('cmv_attribution', models.ForeignKey(blank=True, help_text='Reviewer-set link to the responsible positive draw. Never auto-inferred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.cmvquantitative')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='registry.recipient')),
                ('rejection_attribution', models.ForeignKey(blank=True, help_text='Reviewer-set link to the responsible rejection episode. Never auto-inferred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.rejectionepisode')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHospitalization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, help_text='Null = still admitted.', null=True)),
                ('reason', models.CharField(help_text='All-cause reason. Free text — never exported (leak vector).', max_length=120)),
                ('disposition', models.CharField(blank=True, choices=[('discharged_home', 'Discharged home'), ('transferred', 'Transferred'), ('died', 'Died'), ('against_advice', 'Against medical advice')], max_length=16)),
                ('cmv_attributable', models.BooleanField(default=False, help_text='Honest-denominator flag (US 36): reviewer judgement that the admission is CMV-attributable. Independent of cmv_attribution.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cmv_attribution', models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewer-set link to the responsible positive draw. Never auto-inferred.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmvquantitative')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient')),
                ('rejection_attribution', models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewer-set link to the responsible rejection episode. Never auto-inferred.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.rejectionepisode')),
            ],
            options={
                'verbose_name': 'historical hospitalization',
                'verbose_name_plural': 'historical hospitalizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
