# Generated by Django 5.1.15 on 2026-06-23 00:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_pipelinerun_aliquot_historicalaliquot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('citation', models.CharField(blank=True, default='', max_length=240)),
                ('content_sha256', models.CharField(help_text='SHA-256 over the frozen accession set.', max_length=64, unique=True)),
                ('pinned_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalpipelinerun',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpipelinerun',
            name='input_manifest_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the input manifest — the idempotency key.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalpipelinerun',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpipelinerun',
            name='tool_versions',
            field=models.TextField(blank=True, default='', help_text='Free-text tool/version provenance. Never exported.'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='input_manifest_sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of the input manifest — the idempotency key.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='tool_versions',
            field=models.TextField(blank=True, default='', help_text='Free-text tool/version provenance. Never exported.'),
        ),
        migrations.CreateModel(
            name='GenotypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_type', models.CharField(choices=[('sanger', 'Sanger'), ('qpcr', 'qPCR')], max_length=8)),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genotyping_results', to='registry.aliquot')),
                ('cmv_episode_anchor', models.ForeignKey(blank=True, help_text='Optional anchor to a dated positive QNAT draw (DEC-019).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genotyping_results', to='registry.cmvquantitative')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genotyping_results', to='registry.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGenotypeCall',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('locus', models.CharField(max_length=16)),
                ('allele', models.CharField(max_length=32)),
                ('sanger_call', models.CharField(blank=True, choices=[('R', 'Resolved'), ('F', 'Failed-QC'), ('N', 'No-amplicon')], help_text='Sanger R/F/N taxonomy; null for a qPCR-derived call.', max_length=1, null=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical genotype call',
                'verbose_name_plural': 'historical genotype calls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGenotypingResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assay_type', models.CharField(choices=[('sanger', 'Sanger'), ('qpcr', 'qPCR')], max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aliquot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.aliquot')),
                ('cmv_episode_anchor', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional anchor to a dated positive QNAT draw (DEC-019).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmvquantitative')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pipeline_run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.pipelinerun')),
            ],
            options={
                'verbose_name': 'historical genotyping result',
                'verbose_name_plural': 'historical genotyping results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQpcrDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
            ],
            options={
                'verbose_name': 'historical qpcr detail',
                'verbose_name_plural': 'historical qpcr details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReferenceSet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('citation', models.CharField(blank=True, default='', max_length=240)),
                ('content_sha256', models.CharField(db_index=True, help_text='SHA-256 over the frozen accession set.', max_length=64)),
                ('pinned_at', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reference set',
                'verbose_name_plural': 'historical reference sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSangerDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('raw_ab1_sha256', models.CharField(db_index=True, max_length=64)),
                ('raw_ab1_path', models.CharField(max_length=255)),
                ('consensus_sequence', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('edited_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Editor of the reviewed consensus (attribution). Never exported.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
            ],
            options={
                'verbose_name': 'historical sanger detail',
                'verbose_name_plural': 'historical sanger details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QpcrDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qpcr_details', to='registry.genotypingresult')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalQpcrProbeReading',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('probe', models.CharField(max_length=16)),
                ('call', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('I', 'Indeterminate')], max_length=1)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qpcr_detail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.qpcrdetail')),
            ],
            options={
                'verbose_name': 'historical qpcr probe reading',
                'verbose_name_plural': 'historical qpcr probe readings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QpcrProbeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe', models.CharField(max_length=16)),
                ('call', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('I', 'Indeterminate')], max_length=1)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qpcr_readings_entered', to=settings.AUTH_USER_MODEL)),
                ('qpcr_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe_readings', to='registry.qpcrdetail')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qpcr_readings_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReferenceAccession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('accession', models.CharField(max_length=32)),
                ('genotype', models.CharField(max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference_set', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.referenceset')),
            ],
            options={
                'verbose_name': 'historical reference accession',
                'verbose_name_plural': 'historical reference accessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalpipelinerun',
            name='reference_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='SHA-pinned GenBank reference set used for BLASTn assignment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.referenceset'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='reference_set',
            field=models.ForeignKey(blank=True, help_text='SHA-pinned GenBank reference set used for BLASTn assignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_runs', to='registry.referenceset'),
        ),
        migrations.CreateModel(
            name='SangerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ab1_sha256', models.CharField(max_length=64, unique=True)),
                ('raw_ab1_path', models.CharField(max_length=255)),
                ('consensus_sequence', models.TextField(blank=True, default='')),
                ('edited_by', models.ForeignKey(blank=True, help_text='Editor of the reviewed consensus (attribution). Never exported.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanger_consensus_edits', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanger_details', to='registry.genotypingresult')),
            ],
        ),
        migrations.CreateModel(
            name='GenotypeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus', models.CharField(max_length=16)),
                ('allele', models.CharField(max_length=32)),
                ('sanger_call', models.CharField(blank=True, choices=[('R', 'Resolved'), ('F', 'Failed-QC'), ('N', 'No-amplicon')], help_text='Sanger R/F/N taxonomy; null for a qPCR-derived call.', max_length=1, null=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genotype_calls_entered', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genotype_calls_reviewed', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='registry.genotypingresult')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('is_locked', False), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='genotypecall_locked_requires_reviewer'), models.CheckConstraint(condition=models.Q(('is_locked', False), models.Q(('reviewed_by', models.F('entered_by')), _negated=True), _connector='OR'), name='genotypecall_reviewer_differs_when_locked')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceAccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=32)),
                ('genotype', models.CharField(max_length=32)),
                ('reference_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessions', to='registry.referenceset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reference_set', 'accession'), name='referenceaccession_unique_per_set')],
            },
        ),
    ]
