# Generated by Django 5.1.15 on 2026-06-23 06:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_qpcrprobereading_qpcrprobereading_indeterminate_requires_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConcordancePair',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('concordance_call', models.CharField(blank=True, choices=[('indeterminate', 'Indeterminate'), ('discordant', 'Discordant'), ('concordant', 'Concordant'), ('high_confidence', 'High confidence')], default='', help_text="Reviewer-set tier. Never auto-overwritten by the suggestion; false precision is recorded as 'indeterminate'.", max_length=16)),
                ('superinfection_status', models.CharField(choices=[('none', 'None'), ('candidate', 'Candidate'), ('confirmed', 'Confirmed')], default='none', help_text="Mixed-infection donor-derived superinfection flag. Only 'confirmed' upgrades the recipient's source_label to donor_derived; 'candidate' does not.", max_length=12)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comparator_result', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional second strain to compare against. Absent -> < 2 co-resolved loci -> indeterminate (the honest grading).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipient')),
                ('recipient_result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical concordance pair',
                'verbose_name_plural': 'historical concordance pairs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConcordancePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concordance_call', models.CharField(blank=True, choices=[('indeterminate', 'Indeterminate'), ('discordant', 'Discordant'), ('concordant', 'Concordant'), ('high_confidence', 'High confidence')], default='', help_text="Reviewer-set tier. Never auto-overwritten by the suggestion; false precision is recorded as 'indeterminate'.", max_length=16)),
                ('superinfection_status', models.CharField(choices=[('none', 'None'), ('candidate', 'Candidate'), ('confirmed', 'Confirmed')], default='none', help_text="Mixed-infection donor-derived superinfection flag. Only 'confirmed' upgrades the recipient's source_label to donor_derived; 'candidate' does not.", max_length=12)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('comparator_result', models.ForeignKey(blank=True, help_text='Optional second strain to compare against. Absent -> < 2 co-resolved loci -> indeterminate (the honest grading).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.genotypingresult')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concordance_pairs', to='registry.recipient')),
                ('recipient_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.genotypingresult')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concordance_pairs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('comparator_result', models.F('recipient_result')), _negated=True), name='concordancepair_not_self_comparison')],
            },
        ),
    ]
