# Generated by Django 5.1.15 on 2026-08-04 02:31
#
# Slice 17. Stamps every existing serology row with the assay reagent generation
# that produced it, so results either side of the 2026-06-03 SPMC advisory can be
# interpreted against the ranges that were actually in force (DEC-030 decision 2).
#
# No value is rewritten. There is no unit conversion and no rescaling: the freeze
# ruling means no stored measurement is ever re-interpreted, and DEC-032 confirms
# the unit never changed. This migration only labels rows.
#
# The rule lives in serology_ranges.generation_for and is unit-tested at the
# inclusive 2026-06-03 boundary, so this migration holds no logic of its own.

from django.db import migrations, models

from subay.registry.serology_ranges import generation_for


def stamp_reagent_generation(apps, schema_editor):
    """Backfill by CALLING generation_for, never by re-expressing its boundary.

    Deliberately a row loop rather than two bulk `drawn_date__lt` updates. The
    ORM version would be one statement instead of a scan, but it would restate
    the inclusive boundary in a second place, and this migration would then not
    follow if that boundary were ever corrected. Calling the function is what
    makes its unit test at the 2026-06-03 edge cover this code too, which is the
    agreed reason no migration-test harness was added.

    Study scale makes the loop free: this is a few hundred rows at most.
    """
    for model_name in ("CMVSerology", "HistoricalCMVSerology"):
        Model = apps.get_model("registry", model_name)
        rows = list(Model.objects.all())
        for row in rows:
            row.reagent_generation = generation_for(row.drawn_date)
        Model.objects.bulk_update(rows, ["reagent_generation"], batch_size=500)


def unstamp_reagent_generation(apps, schema_editor):
    """Reverse leaves the column blank rather than guessing. Nothing is lost:
    the column is additive and no measurement was touched on the way in."""
    for name in ("CMVSerology", "HistoricalCMVSerology"):
        apps.get_model("registry", name).objects.update(reagent_generation="")


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_assign_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmvserology',
            name='reagent_generation',
            field=models.CharField(blank=True, choices=[('gen1', '1st generation (before 2026-06-03)'), ('gen2', '2nd generation (from 2026-06-03)')], help_text='Assay reagent generation that produced this result. Leave blank to default from the draw date (2nd gen from 2026-06-03). Set it by hand only for a late-entered sample that was run on 1st-generation reagent.', max_length=4),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='reagent_generation',
            field=models.CharField(blank=True, choices=[('gen1', '1st generation (before 2026-06-03)'), ('gen2', '2nd generation (from 2026-06-03)')], help_text='Assay reagent generation that produced this result. Leave blank to default from the draw date (2nd gen from 2026-06-03). Set it by hand only for a late-entered sample that was run on 1st-generation reagent.', max_length=4),
        ),
        migrations.RunPython(stamp_reagent_generation, unstamp_reagent_generation),
    ]
