# Generated by Django 5.1.15 on 2026-08-04 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_slice17_reagent_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.CheckConstraint(condition=models.Q(('reagent_generation__in', ['gen1', 'gen2', ''])), name='cmvserology_known_reagent_generation'),
        ),
    ]
