# Generated by Django 5.1.15 on 2026-08-04 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_slice17_known_reagent_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cmvserology',
            name='repeats',
            field=models.ForeignKey(blank=True, help_text='The earlier equivocal draw this result repeats. Leave blank for an ordinary draw. Setting it is what discharges that draw from the repeat-draw worklist.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repeated_by', to='registry.cmvserology'),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='repeats',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The earlier equivocal draw this result repeats. Leave blank for an ordinary draw. Setting it is what discharges that draw from the repeat-draw worklist.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmvserology'),
        ),
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.CheckConstraint(condition=models.Q(('repeats__isnull', True), models.Q(('repeats', models.F('id')), _negated=True), _connector='OR'), name='cmvserology_repeat_is_not_itself'),
        ),
    ]
