# Generated by Django 5.1.15 on 2026-06-19 07:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_historicalothercondition_othercondition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(choices=[('annexed_holiday', 'Annexed holiday'), ('emergency_closure', 'Emergency closure')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Annex/clause/memo cite. Free text — never exported.', max_length=120)),
                ('closes_clinic', models.BooleanField(default=True)),
                ('closes_lab', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='historicalrecipientvisit',
            old_name='visit_date',
            new_name='actual_visit_date',
        ),
        migrations.RenameField(
            model_name='recipientvisit',
            old_name='visit_date',
            new_name='actual_visit_date',
        ),
        migrations.AddField(
            model_name='historicalrecipientvisit',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed_visit', 'Missed visit')], default='completed', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalrecipientvisit',
            name='timepoint_label',
            field=models.CharField(choices=[('pre_kt', 'pre_kt'), ('day_7', 'day_7'), ('day_30', 'day_30'), ('day_90', 'day_90'), ('day_120', 'day_120'), ('day_180', 'day_180')], default='day_7', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientvisit',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed_visit', 'Missed visit')], default='completed', max_length=12),
        ),
        migrations.AddField(
            model_name='recipientvisit',
            name='timepoint_label',
            field=models.CharField(choices=[('pre_kt', 'pre_kt'), ('day_7', 'day_7'), ('day_30', 'day_30'), ('day_90', 'day_90'), ('day_120', 'day_120'), ('day_180', 'day_180')], default='day_7', max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DonorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='registry.donor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClosureDay',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('annexed_holiday', 'Annexed holiday'), ('emergency_closure', 'Emergency closure')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Annex/clause/memo cite. Free text — never exported.', max_length=120)),
                ('closes_clinic', models.BooleanField(default=True)),
                ('closes_lab', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical closure day',
                'verbose_name_plural': 'historical closure days',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDonorVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.donor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical donor visit',
                'verbose_name_plural': 'historical donor visits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
