# Generated by Django 5.1.15 on 2026-06-22 07:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_historicalmedicationcourse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.CharField(choices=[('plasma', 'Plasma'), ('serum', 'Serum'), ('pbmc', 'PBMC'), ('whole_blood', 'Whole blood'), ('urine', 'Urine')], max_length=12)),
                ('collected_date', models.DateField()),
                ('initial_volume_ul', models.DecimalField(decimal_places=2, help_text='As-banked volume, µL. The ledger ceiling.', max_digits=10)),
                ('recipient_visit', models.ForeignKey(blank=True, help_text='Opportunistic per-timepoint anchor (slice 03). Null = unanchored straw.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliquots', to='registry.recipientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAliquot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('matrix', models.CharField(choices=[('plasma', 'Plasma'), ('serum', 'Serum'), ('pbmc', 'PBMC'), ('whole_blood', 'Whole blood'), ('urine', 'Urine')], max_length=12)),
                ('collected_date', models.DateField()),
                ('initial_volume_ul', models.DecimalField(decimal_places=2, help_text='As-banked volume, µL. The ledger ceiling.', max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_visit', models.ForeignKey(blank=True, db_constraint=False, help_text='Opportunistic per-timepoint anchor (slice 03). Null = unanchored straw.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.recipientvisit')),
            ],
            options={
                'verbose_name': 'historical aliquot',
                'verbose_name_plural': 'historical aliquots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPipelineRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pipeline run',
                'verbose_name_plural': 'historical pipeline runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSequencingAliquot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('destruction_certificate', models.CharField(help_text='PGC destruction certificate ref per MOA (default per-sample). Free text — never exported (leak vector).', max_length=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aliquot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.aliquot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sequencing aliquot',
                'verbose_name_plural': 'historical sequencing aliquots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalThawEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('thawed_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aliquot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.aliquot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical thaw event',
                'verbose_name_plural': 'historical thaw events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConsumptionEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('volume_ul', models.DecimalField(decimal_places=2, help_text='Volume drawn, µL. Must be > 0.', max_digits=10)),
                ('consumed_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aliquot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.aliquot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pipeline_run', models.ForeignKey(blank=True, db_constraint=False, help_text='Analysis run that consumed this volume (slice 10). Null = not yet linked.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.pipelinerun')),
            ],
            options={
                'verbose_name': 'historical consumption event',
                'verbose_name_plural': 'historical consumption events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SequencingAliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('destruction_certificate', models.CharField(help_text='PGC destruction certificate ref per MOA (default per-sample). Free text — never exported (leak vector).', max_length=120)),
                ('aliquot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_aliquot', to='registry.aliquot')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ul', models.DecimalField(decimal_places=2, help_text='Volume drawn, µL. Must be > 0.', max_digits=10)),
                ('consumed_date', models.DateField()),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_events', to='registry.aliquot')),
                ('pipeline_run', models.ForeignKey(blank=True, help_text='Analysis run that consumed this volume (slice 10). Null = not yet linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='registry.pipelinerun')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('volume_ul__gt', 0)), name='consumptionevent_volume_positive')],
            },
        ),
        migrations.CreateModel(
            name='ThawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thawed_date', models.DateField()),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_events', to='registry.aliquot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aliquot',), name='thawevent_single_use_no_refreeze')],
            },
        ),
    ]
