# Generated by Django 5.1.15 on 2026-06-23 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_referenceset_historicalpipelinerun_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qpcrprobereading',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('call', 'I'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='qpcrprobereading_indeterminate_requires_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='qpcrprobereading',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('call', 'I'), _negated=True), models.Q(('reviewed_by', models.F('entered_by')), _negated=True), _connector='OR'), name='qpcrprobereading_reviewer_differs_when_indeterminate'),
        ),
    ]
