# Generated by Django 5.1.15 on 2026-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_historicalconcordancepair_concordancepair'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicationcourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course_type', 'treatment'), _negated=True), models.Q(('completed_per_protocol__isnull', True), ('early_discontinuation_reason', '')), _connector='OR'), name='medicationcourse_no_prophylaxis_fields_on_treatment'),
        ),
        migrations.AddConstraint(
            model_name='medicationcourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course_type', 'prophylaxis'), _negated=True), models.Q(('dose_reduction_count__isnull', True), ('dose_reduction_reason', '')), _connector='OR'), name='medicationcourse_no_treatment_fields_on_prophylaxis'),
        ),
    ]
