# Generated by Django 5.1.15 on 2026-06-24 00:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_medicationcourse_medicationcourse_no_prophylaxis_fields_on_treatment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResistanceCall',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('locus', models.CharField(choices=[('UL97', 'UL97'), ('UL54', 'UL54')], max_length=8)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('F', 'Failed-QC'), ('N', 'No-amplicon')], help_text='R/F/N — the same Sanger taxonomy as a GenotypeCall.', max_length=1)),
                ('qnat_iu_ml', models.DecimalField(blank=True, decimal_places=2, help_text='COBAS 5000 IU/mL viral load AT the call (amplification-floor context). A value, never a date; null when no QNAT was recorded at the call.', max_digits=12, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.genotypingresult')),
            ],
            options={
                'verbose_name': 'historical resistance call',
                'verbose_name_plural': 'historical resistance calls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResistanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus', models.CharField(choices=[('UL97', 'UL97'), ('UL54', 'UL54')], max_length=8)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('F', 'Failed-QC'), ('N', 'No-amplicon')], help_text='R/F/N — the same Sanger taxonomy as a GenotypeCall.', max_length=1)),
                ('qnat_iu_ml', models.DecimalField(blank=True, decimal_places=2, help_text='COBAS 5000 IU/mL viral load AT the call (amplification-floor context). A value, never a date; null when no QNAT was recorded at the call.', max_digits=12, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resistance_calls', to='registry.genotypingresult')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalResistanceVariant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('variant', models.CharField(help_text='Variant/mutation code, e.g. C592G, M460V.', max_length=32)),
                ('tier', models.CharField(choices=[('established', 'Established'), ('polymorphism', 'Polymorphism'), ('unknown', 'Unknown')], max_length=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resistance_call', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.resistancecall')),
            ],
            options={
                'verbose_name': 'historical resistance variant',
                'verbose_name_plural': 'historical resistance variants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResistanceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(help_text='Variant/mutation code, e.g. C592G, M460V.', max_length=32)),
                ('tier', models.CharField(choices=[('established', 'Established'), ('polymorphism', 'Polymorphism'), ('unknown', 'Unknown')], max_length=12)),
                ('resistance_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='registry.resistancecall')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resistancecall',
            constraint=models.CheckConstraint(condition=models.Q(('locus__in', ('UL97', 'UL54'))), name='resistancecall_locus_is_ul97_or_ul54'),
        ),
    ]
