# Generated by Django 5.1.15 on 2026-06-24 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_historicalresistancecall_resistancecall_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genotypecall',
            name='genotypecall_locked_requires_reviewer',
        ),
        migrations.RemoveConstraint(
            model_name='genotypecall',
            name='genotypecall_reviewer_differs_when_locked',
        ),
        # DEC-022: rename the bespoke gate onto the shared mixin's names,
        # preserving any existing call data (RenameField, not drop+recreate).
        migrations.RenameField(
            model_name='genotypecall',
            old_name='is_locked',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='genotypecall',
            old_name='reviewed_at',
            new_name='verified_at',
        ),
        migrations.RenameField(
            model_name='genotypecall',
            old_name='reviewed_by',
            new_name='verified_by',
        ),
        migrations.RenameField(
            model_name='historicalgenotypecall',
            old_name='is_locked',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='historicalgenotypecall',
            old_name='reviewed_at',
            new_name='verified_at',
        ),
        migrations.RenameField(
            model_name='historicalgenotypecall',
            old_name='reviewed_by',
            new_name='verified_by',
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cmvserology',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druglevel',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druglevel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='druglevel',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druglevel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='entered_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcmvserology',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldruglevel',
            name='entered_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldruglevel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldruglevel',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldruglevel',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrejectionepisode',
            name='entered_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrejectionepisode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrejectionepisode',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrejectionepisode',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectionepisode',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectionepisode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejectionepisode',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejectionepisode',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genotypecall',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('entered_by__isnull', False), ('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='cmvserology_verification_verified_requires_verifier'),
        ),
        migrations.AddConstraint(
            model_name='cmvserology',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('verified_by', models.F('entered_by')), _negated=True), _connector='OR'), name='cmvserology_verification_verifier_differs_when_verified'),
        ),
        migrations.AddConstraint(
            model_name='druglevel',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('entered_by__isnull', False), ('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='druglevel_verification_verified_requires_verifier'),
        ),
        migrations.AddConstraint(
            model_name='druglevel',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('verified_by', models.F('entered_by')), _negated=True), _connector='OR'), name='druglevel_verification_verifier_differs_when_verified'),
        ),
        migrations.AddConstraint(
            model_name='genotypecall',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('entered_by__isnull', False), ('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='genotypecall_verification_verified_requires_verifier'),
        ),
        migrations.AddConstraint(
            model_name='genotypecall',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('verified_by', models.F('entered_by')), _negated=True), _connector='OR'), name='genotypecall_verification_verifier_differs_when_verified'),
        ),
        migrations.AddConstraint(
            model_name='rejectionepisode',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('entered_by__isnull', False), ('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='rejectionepisode_verification_verified_requires_verifier'),
        ),
        migrations.AddConstraint(
            model_name='rejectionepisode',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('verified_by', models.F('entered_by')), _negated=True), _connector='OR'), name='rejectionepisode_verification_verifier_differs_when_verified'),
        ),
    ]
