# Generated by Django 5.1.15 on 2026-06-24 02:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_alter_genotypecall_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProtocolDeviation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deviation_type', models.CharField(choices=[('late_release', 'Late release'), ('missed_release', 'Missed release')], max_length=16)),
                ('caused_harm', models.BooleanField(default=False)),
                ('is_research_related_sae', models.BooleanField(default=False)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quantitative', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmvquantitative')),
            ],
            options={
                'verbose_name': 'historical protocol deviation',
                'verbose_name_plural': 'historical protocol deviations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReleaseEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('released_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quantitative', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.cmvquantitative')),
            ],
            options={
                'verbose_name': 'historical release event',
                'verbose_name_plural': 'historical release events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProtocolDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(choices=[('late_release', 'Late release'), ('missed_release', 'Missed release')], max_length=16)),
                ('caused_harm', models.BooleanField(default=False)),
                ('is_research_related_sae', models.BooleanField(default=False)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('quantitative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_deviations', to='registry.cmvquantitative')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_date', models.DateField()),
                ('quantitative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_events', to='registry.cmvquantitative')),
            ],
        ),
    ]
